export const DB = [
    {
      userId: 1,
      username: 'john_doe',
      name: 'John Doe',
      bio: 'Tech enthusiast and coffee lover. Tweets about tech, travel, and life.',
      profilePicture: 'https://randomuser.me/api/portraits/men/1.jpg',
      followersCount: 250,
      followingCount: 180,
      tweets: [
        {
          tweetId: 1,
          content: 'Just launched my new project! Excited to share it with everyone. #launch',
          createdAt: '2024-09-30T12:00:00Z',
          likes: 25,
          retweets: 10,
          comments: 5,
        },
        {
          tweetId: 2,
          content: 'Anyone else excited about the new React features? #ReactJS',
          createdAt: '2024-09-29T15:30:00Z',
          likes: 30,
          retweets: 5,
          comments: 2,
        },
        {
          tweetId: 3,
          content: 'Just finished a great book on JavaScript! Highly recommend. 📚 #BookLover',
          createdAt: '2024-09-28T10:00:00Z',
          likes: 18,
          retweets: 3,
          comments: 1,
        },
      ],
    },
    {
      userId: 2,
      username: 'jane_smith',
      name: 'Jane Smith',
      bio: 'Digital marketing specialist. Love to travel and take photos.',
      profilePicture: 'https://randomuser.me/api/portraits/women/2.jpg',
      followersCount: 300,
      followingCount: 150,
      tweets: [
        {
          tweetId: 1,
          content: 'Just returned from a beautiful trip to Italy! 🇮🇹 #TravelDiaries',
          createdAt: '2024-09-29T18:45:00Z',
          likes: 45,
          retweets: 15,
          comments: 7,
        },
        {
          tweetId: 2,
          content: 'Exploring new digital marketing trends for 2024! #Marketing',
          createdAt: '2024-09-27T14:30:00Z',
          likes: 28,
          retweets: 4,
          comments: 3,
        },
      ],
    },
    {
      userId: 3,
      username: 'mark_twain',
      name: 'Mark Twain',
      bio: 'Writer and storyteller. Sharing thoughts on literature and life.',
      profilePicture: 'https://randomuser.me/api/portraits/men/3.jpg',
      followersCount: 200,
      followingCount: 100,
      tweets: [
        {
          tweetId: 1,
          content: 'A good book is a friend that never betrays. #Reading',
          createdAt: '2024-09-25T10:15:00Z',
          likes: 20,
          retweets: 5,
          comments: 3,
        },
        {
          tweetId: 2,
          content: 'Writing is easy. All you have to do is cross out the wrong words. #Writing',
          createdAt: '2024-09-23T12:00:00Z',
          likes: 15,
          retweets: 2,
          comments: 1,
        },
        {
          tweetId: 3,
          content: 'Let us be thankful for the fools. But for them, the rest of us could not succeed. #Wisdom',
          createdAt: '2024-09-21T09:00:00Z',
          likes: 10,
          retweets: 1,
          comments: 0,
        },
      ],
    },
    {
      userId: 4,
      username: 'sara_lee',
      name: 'Sara Lee',
      bio: 'Food blogger and recipe creator. Sharing my culinary adventures!',
      profilePicture: 'https://randomuser.me/api/portraits/women/4.jpg',
      followersCount: 450,
      followingCount: 300,
      tweets: [
        {
          tweetId: 1,
          content: 'Tried a new recipe today! Check out my blog for the details. 🍽️ #Foodie',
          createdAt: '2024-09-28T13:00:00Z',
          likes: 60,
          retweets: 20,
          comments: 10,
        },
        {
          tweetId: 2,
          content: 'Food is my love language! What’s yours? #FoodLove',
          createdAt: '2024-09-26T14:00:00Z',
          likes: 50,
          retweets: 15,
          comments: 8,
        },
        {
          tweetId: 3,
          content: 'Can’t wait to share my favorite fall recipes! 🍁 #FallCooking',
          createdAt: '2024-09-24T16:30:00Z',
          likes: 40,
          retweets: 12,
          comments: 4,
        },
      ],
    },
    {
      userId: 5,
      username: 'alice_wonder',
      name: 'Alice Wonderland',
      bio: 'Dreamer and artist. Exploring creativity in everyday life.',
      profilePicture: 'https://randomuser.me/api/portraits/women/5.jpg',
      followersCount: 500,
      followingCount: 400,
      tweets: [
        {
          tweetId: 1,
          content: 'Creating art is like dreaming with colors. 🎨 #ArtLife',
          createdAt: '2024-09-26T14:30:00Z',
          likes: 35,
          retweets: 8,
          comments: 4,
        },
        {
          tweetId: 2,
          content: 'Art is not freedom from discipline, but disciplined freedom. #ArtQuotes',
          createdAt: '2024-09-24T11:15:00Z',
          likes: 20,
          retweets: 5,
          comments: 2,
        },
        {
          tweetId: 3,
          content: 'Just finished a new painting! Can’t wait to show it off! #ArtCommunity',
          createdAt: '2024-09-22T13:30:00Z',
          likes: 30,
          retweets: 6,
          comments: 3,
        },
      ],
    },
    {
      userId: 6,
      username: 'charlie_brown',
      name: 'Charlie Brown',
      bio: 'Aspiring musician. Love to share my journey in music.',
      profilePicture: 'https://randomuser.me/api/portraits/men/6.jpg',
      followersCount: 100,
      followingCount: 75,
      tweets: [
        {
          tweetId: 1,
          content: 'Just finished writing a new song! Can’t wait to share it! 🎶 #MusicLife',
          createdAt: '2024-09-24T16:00:00Z',
          likes: 18,
          retweets: 4,
          comments: 1,
        },
        {
          tweetId: 2,
          content: 'Music is the shorthand of emotion. 🎵 #MusicQuote',
          createdAt: '2024-09-22T09:00:00Z',
          likes: 12,
          retweets: 3,
          comments: 0,
        },
      ],
    },
    {
      userId: 7,
      username: 'david_brown',
      name: 'David Brown',
      bio: 'Gadget lover and tech reviewer. Sharing insights on the latest tech.',
      profilePicture: 'https://randomuser.me/api/portraits/men/7.jpg',
      followersCount: 275,
      followingCount: 125,
      tweets: [
        {
          tweetId: 1,
          content: 'Just got my hands on the latest smartphone! Review coming soon. 📱 #TechReview',
          createdAt: '2024-09-23T11:00:00Z',
          likes: 30,
          retweets: 10,
          comments: 5,
        },
        {
          tweetId: 2,
          content: 'Can’t believe how fast technology is evolving! #FutureTech',
          createdAt: '2024-09-21T14:30:00Z',
          likes: 20,
          retweets: 8,
          comments: 2,
        },
      ],
    },
    {
      userId: 8,
      username: 'emma_stone',
      name: 'Emma Stone',
      bio: 'Nature lover and photographer. Capturing the beauty of the world.',
      profilePicture: 'https://randomuser.me/api/portraits/women/6.jpg',
      followersCount: 600,
      followingCount: 300,
      tweets: [
        {
          tweetId: 1,
          content: 'The beauty of nature never ceases to amaze me! 🌲 #NaturePhotography',
          createdAt: '2024-09-22T09:45:00Z',
          likes: 80,
          retweets: 25,
          comments: 12,
        },
        {
          tweetId: 2,
          content: 'Nature is the art of God. 🌼 #NatureLover',
          createdAt: '2024-09-20T14:00:00Z',
          likes: 50,
          retweets: 10,
          comments: 5,
        },
        {
          tweetId: 3,
          content: 'Always finding inspiration in the great outdoors. 🍃 #Photography',
          createdAt: '2024-09-18T10:30:00Z',
          likes: 40,
          retweets: 15,
          comments: 8,
        },
      ],
    },
  ];
  
  